sudo: true

services:
 - docker

language: java

jdk:
  - oraclejdk8

before_install:
 - docker run --name iot-redis -p 6379:6379 -d redis:3.2.6-alpine

install: ./gradlew --version

script: ./gradlew release build
